# Generated by Django 6.0.4 on 2026-04-30 20:19

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_remove_announcement_category_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_category_name_case_insensitive'),
        ),
    ]
