# Generated by Django 6.0.4 on 2026-05-07 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_announcement_author_announcement_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_case_insensitive',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='image',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='announcements.category'),
        ),
    ]
