# Generated by Django 6.0.4 on 2026-05-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_announcement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pastor', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='sermons/')),
                ('youtube_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
