# Generated by Django 6.0.4 on 2026-05-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0011_event_eventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDevotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bible_verse', models.CharField(max_length=255)),
                ('scripture_text', models.TextField()),
                ('message', models.TextField()),
                ('prayer', models.TextField()),
                ('devotional_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
