# Generated by Django 6.0.4 on 2026-06-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0015_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField()),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
