# Generated by Django 6.0.4 on 2026-06-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0016_livestream'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleReadingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scripture', models.CharField(max_length=255)),
                ('reading_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
