# Generated by Django 6.0.4 on 2026-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0017_biblereadingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
