# Generated by Django 6.0.4 on 2026-06-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0019_churchbranch'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField()),
                ('is_live', models.BooleanField(default=False)),
            ],
        ),
    ]
