# Generated by Django 6.0.4 on 2026-07-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0021_devotional'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='pdf_notes',
            field=models.FileField(blank=True, null=True, upload_to='sermons/'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='scripture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='sermon_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
